### ISSUE TITLE
How to get this bin - setuptools-golang-build-manylinux-wheels

### ISSUE THREAD

**Issue by gane5hvarma** [asottile/setuptools-golang#119]
When i try to execute `setuptools-golang-build-manylinux-wheels` it says command not found. How do i get this bin in my system

**Comment by gane5hvarma** [comment]
I tried import setuptools_golang and invoked `build_manylinux_wheels()` function. It has thrown me an error
```
running build_ext
      $ GOPATH=/tmp/tmpyndoez56 go get -d
      go: go.mod file not found in current directory or any parent directory; see 'go help modules'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-vh1fkpy0/setup.py", line 28, in <module>
          include_package_data=True,
        File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/_internal/cpython-3.7.12/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
